#include <stdint.h>
#include <float.h>
#include <stddef.h>
#include <string.h>
#include <RF/rf.h>

#include "rfStruct.h"

// Primary rays ///////////////////////////////////////////////////////////////

#define TRACEPIPELINE rfRays
#define TRACEPARAM    rfRayData*
#define TRACEPARAMPASSBYREFERENCE (0)

#define TRACEHIT  rfHitFcn
#define TRACEVOID rfVoidFcn

// Set to non-zero to enable ray distance clipping : new clipdist parameter,
// TRACECLIP() is called
#define TRACEDISTCLIP (0)

// Set to non-zero if roots have to be resolved from scratch to match origin
#define TRACERESOLVEROOT (0)

// Set to non-zero if roots have to be displaced to match origin
#define TRACEDISPLACEROOT (0)

// Set to non-zero if roots were generated by quad tracing
#define TRACEQUADROOT (0)

// Do we want intersection points, barycentric coordinates, hit point
// distance, etc.?
#define TRACEHITMODELDATA  (0)
#define TRACEHITOBJECTDATA (0)
#define TRACEHITVECTOR     (0)
#define TRACEHITPOINT      (0)
#define TRACEHITUV         (0)
#define TRACEHITDATA       (1)
#define TRACEHITDIST       (1)
#define TRACEHITPLANE      (1)
#define TRACEHITSIDE       (0)
#define TRACEHITROOT       (0)
#define TRACEHITMATRIX     (0)

RF_INLINE void rfHitFcn(rfRayData* rayData,
                        void*  modeldata,
                        void*  objectdata,
                        float* dir,
                        float* hitpt,
                        float* hituv,
                        void*  tridata,
                        float  hitdist,
                        float* n,
                        int    hitside,
                        rfRoot root,
                        float* matrix)
{
  rayData->hit = 1;
  rayData->minT = hitdist;

  rfTriangleData* data = (rfTriangleData*)tridata;
  rayData->triID = data->triID;
  rayData->matID = data->matID;

  rayData->normal[0] = n[0];
  rayData->normal[1] = n[1];
  rayData->normal[2] = n[2];
}

RF_INLINE void rfVoidFcn(rfRayData* rayData, float* dir, rfRoot root)
{
  rayData->hit = 0;
}

// Assemble pipeline for primary rays
#include <RF/rftrace.h>

